# Generated by Django 5.0.4 on 2024-04-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_portal',
            name='answer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='test_portal',
            name='option1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='test_portal',
            name='option2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='test_portal',
            name='option3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='test_portal',
            name='option4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='test_portal',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
